package com.bluebillywig.bbplayer;

/**
 * Placeholder for New Architecture (Fabric/TurboModules).
 * The actual spec is generated by React Native codegen during build.
 * This file allows the project to compile before codegen runs.
 *
 * During New Architecture builds, this file is replaced by the codegen-generated spec.
 */

// The codegen-generated spec will be in:
// android/build/generated/source/codegen/java/com/bluebillywig/bbplayer/NativeBBPlayerModuleSpec.java
